name: Test Semgrep Rules

on: [push]

permissions: {}

jobs:
  validate-and-test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Validate Rules
        run: |
          cd packages/semgrep-action
          bin/validate-rules
        shell: bash

      - name: Run Rule Tests
        run: |
          cd packages/semgrep-action
          bin/test
        shell: bash
