# TODO: finish implementation of this workflow, currently deprioritised but leaving this in as a reminder
name: 'MetaMask Security Action Webhook'

on:
  repository_dispatch:
    types: [code_scanning_alert]

jobs:
  run-security-scan:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: echo stuff
        run: |
          echo " GOT IT"
        shell: bash
